defaults: &defaults
  host: 10.0.2.2
  port: 27017

development:
  <<: *defaults
  database: nonsense_development

test:
  <<: *defaults
  database: nonsense_test

# set these environment variables on your prod server
production:
  <<: *defaults
  database: nonsense
  username: <%= ENV['MONGO_USERNAME'] %>
  password: <%= ENV['MONGO_PASSWORD'] %>
